import type { Emotion } from './types';

export const EMOTION_TO_PLANT: Record<Emotion, string> = {
  happy: 'Sunflower',
  sad: 'Bleeding Heart',
  angry: 'Cactus',
  anxious: 'Passionflower',
  calm: 'Lavender',
  grateful: 'Hydrangea',
  love: 'Rose',
  hope: 'Daffodil',
  excited: 'Bird of Paradise',
  lonely: 'Forget-Me-Not',
  proud: 'Orchid',
  confused: 'Wisteria',
  peaceful: 'Lotus',
  nostalgic: 'Cherry Blossom',
  jealous: 'Nightshade',
  inspired: 'Iris',
  guilty: 'Thistle',
  curious: 'Snapdragon',
  frustrated: 'Bramble',
  content: 'Chamomile',
  overwhelmed: 'Morning Glory',
  brave: 'Protea',
  embarrassed: 'Mimosa',
  surprised: 'Stargazer Lily',
  bored: 'Dandelion',
  determined: 'Gladiolus',
  compassionate: 'Aloe Vera',
  melancholy: 'Bluebell',
  joyful: 'Daisy',
  vulnerable: 'Snowdrop',
};
