// @ts-check
'use strict';

const Jimp = require('jimp-compact');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'assets', 'tiles', 'sliced');
const TILE_REQUIRES_PATH = path.join(ROOT, 'src', 'components', 'garden', 'tileRequires.ts');

const TILESETS = [
  { firstgid: 1,   name: 'grass_hills',  columns: 11, tileCount: 77,  src: 'assets/tiles/sprout-lands/ground/Darker_Grass_Hills_Tiles_v2.png' },
  { firstgid: 78,  name: 'soil_hills',   columns: 11, tileCount: 77,  src: 'assets/tiles/sprout-lands/ground/Darker_Soil_Ground_Hills_Tiles.png' },
  { firstgid: 155, name: 'house_walls',  columns: 5,  tileCount: 15,  src: 'assets/tiles/sprout-lands/structures/Wooden_House_Walls_Tilset.png' },
  { firstgid: 170, name: 'house_roof',   columns: 7,  tileCount: 35,  src: 'assets/tiles/sprout-lands/structures/Wooden_House_Roof_Tilset.png' },
  { firstgid: 205, name: 'door_anim',    columns: 18, tileCount: 36,  src: 'assets/tiles/sprout-lands/structures/door animation sprites.png' },
  { firstgid: 241, name: 'fences',       columns: 8,  tileCount: 32,  src: 'assets/tiles/sprout-lands/fences/Fences.png' },
  { firstgid: 273, name: 'fence_gates',  columns: 10, tileCount: 30,  src: 'assets/tiles/sprout-lands/fences/Fence gates animation sprites .png' },
  { firstgid: 303, name: 'paths',        columns: 4,  tileCount: 16,  src: 'assets/tiles/sprout-lands/paths/Paths.png' },
  { firstgid: 319, name: 'trees',        columns: 12, tileCount: 84,  src: 'assets/sprites/objects/trees/Trees, stumps and bushes.png' },
  { firstgid: 403, name: 'water_well',   columns: 2,  tileCount: 4,   src: 'assets/sprites/objects/decorations/Water well.png' },
  { firstgid: 407, name: 'mushrooms',    columns: 12, tileCount: 60,  src: 'assets/sprites/objects/decorations/Mushrooms, Flowers, Stones.png' },
  { firstgid: 467, name: 'signs',        columns: 8,  tileCount: 16,  src: 'assets/sprites/objects/decorations/signs_sides.png' },
];

const TILE_SIZE = 16;

async function sliceTileset(tileset) {
  const srcPath = path.join(ROOT, tileset.src);
  const img = await Jimp.read(srcPath);
  const tileDir = path.join(OUT_DIR, tileset.name);
  fs.mkdirSync(tileDir, { recursive: true });

  for (let localId = 0; localId < tileset.tileCount; localId++) {
    const srcX = (localId % tileset.columns) * TILE_SIZE;
    const srcY = Math.floor(localId / tileset.columns) * TILE_SIZE;
    const tile = img.clone().crop(srcX, srcY, TILE_SIZE, TILE_SIZE);
    await tile.writeAsync(path.join(tileDir, `${localId}.png`));
  }

  console.log(`  ✓ ${tileset.name}: ${tileset.tileCount} tiles`);
  return tileset.tileCount;
}

function generateTileRequires() {
  const lines = [
    '// AUTO-GENERATED by scripts/slice-tiles.js — DO NOT EDIT',
    'export const TILE_IMAGES: Record<number, ReturnType<typeof require>> = {',
  ];

  for (const ts of TILESETS) {
    for (let localId = 0; localId < ts.tileCount; localId++) {
      const gid = ts.firstgid + localId;
      lines.push(`  ${gid}: require('../../../assets/tiles/sliced/${ts.name}/${localId}.png'),`);
    }
  }

  lines.push('};', '');
  fs.writeFileSync(TILE_REQUIRES_PATH, lines.join('\n'));
  console.log(`  ✓ tileRequires.ts written`);
}

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  let total = 0;
  for (const ts of TILESETS) {
    total += await sliceTileset(ts);
  }

  // Write manifest
  const manifest = {};
  for (const ts of TILESETS) {
    manifest[ts.firstgid] = { name: ts.name, tileCount: ts.tileCount, tilesDir: `assets/tiles/sliced/${ts.name}` };
  }
  fs.writeFileSync(path.join(OUT_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2));
  console.log(`  ✓ manifest.json written`);

  generateTileRequires();

  console.log(`\nDone. ${total} tiles sliced across ${TILESETS.length} tilesets.`);
}

main().catch(err => { console.error(err); process.exit(1); });
